on:
  pull_request:
    paths:
      - 'Dockerfile'

name: docker-lint

jobs:
  lint:
    name: run
    runs-on: [ubuntu-latest]
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile with Hadolint
        id: hadolint
        uses: echapmanFromBunnings/dockerlint-hadolint-action@v1.0.0
        with:
          dockerfile: Dockerfile
        continue-on-error: true