name: 'Hadolint-github-ext'
description: |
  Wraps dockerlinting tools in a github friendly wrapper
author: 'echapmanFromBunnings'
branding:
  icon: 'archive'
  color: 'green'
inputs:
  dockerfile:
    description: 'Dockerfile to lint'
    required: true

runs:
  using: "composite"
  steps:
    - name: Lint Dockerfile with Hadolint
      id: hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning
        format: json
        output-file: hadolint_report.json
      continue-on-error: true

    - name: Capture Hadolint Output and Write to Job Summary
      id: capture-output
      run: |          
        # Escape JSON for safer processing
        ESCAPED_OUTPUT=$(jq -c . hadolint_report.json)
        
        # Parse JSON into Markdown Table
        echo "### ðŸ³ Docker Linting Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Line | Column | Level | Code | Message |" >> $GITHUB_STEP_SUMMARY
        echo "|------|--------|-------|------|---------|" >> $GITHUB_STEP_SUMMARY
        
        jq -r '.[] | "| \(.line) | \(.column) | \(.level) | \(.code) | \(.message) |"' hadolint_report.json >> $GITHUB_STEP_SUMMARY
      shell: bash
    - name: Annotate Dockerfile with Hadolint Issues
      run: |
        jq -c '.[]' hadolint_report.json | while read -r issue; do
          LINE=$(echo "$issue" | jq -r '.line')
          COLUMN=$(echo "$issue" | jq -r '.column')
          LEVEL=$(echo "$issue" | jq -r '.level')
          CODE=$(echo "$issue" | jq -r '.code')
          MESSAGE=$(echo "$issue" | jq -r '.message')
          
          # Map LEVEL "info" to "notice"
          if [ "$LEVEL" == "info" ]; then
            LEVEL="notice"
          fi
          
          echo "::${LEVEL} file=Dockerfile,line=$LINE,col=$COLUMN,title=$CODE::$MESSAGE"
        done
      shell: bash
    - name: Format Structured Comment for PR
      id: format-comment
      run: |
        echo "<strong>ðŸš¨ Found Issues in Your Dockerfile ðŸš¨</strong><br>" > hadolint_comment.html
        echo "<table border='1' cellpadding='5' cellspacing='0'>" >> hadolint_comment.html
        echo "<tr><th>Line</th><th>Level</th><th>Message</th><th>Code</th></tr>" >> hadolint_comment.html
        
        # Parse the JSON file, convert numbers to strings and append them to the HTML table
        jq -r '.[] | "<tr><td>" + (.line | tostring) + "</td><td>" + .level + "</td><td>" + .message + "</td><td>" + .code + "</td></tr>"' hadolint_report.json >> hadolint_comment.html
        
        echo "</table>" >> hadolint_comment.html
        echo "LINT_COMMENT<<EOF" >> $GITHUB_ENV
        cat hadolint_comment.html >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        if [ "$(jq 'length' hadolint_report.json)" -eq 0 ]; then
          echo "HADOLINT_EMPTY=yes" >> $GITHUB_ENV
        else
          echo "HADOLINT_EMPTY=no" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Update Pull Request
      uses: thollander/actions-comment-pull-request@v2
      if: env.HADOLINT_EMPTY == 'no'
      with:
        message: "${{ env.LINT_COMMENT }}"
        comment_tag: hadolint
